# Generated by Django 4.2.11 on 2024-04-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list",
            name="list",
        ),
        migrations.AddField(
            model_name="item",
            name="list",
            field=models.TextField(default=""),
        ),
    ]
